### ISSUE TITLE
Ein Admin ist man wenn man Betreiber der Seite ist oder von ihnen angestellt ist.

### ISSUE THREAD

**Issue by LocoVIB** [actofgoods/actofgoods#42]

**Comment by PaulsBecks** [comment]
Ist das eine User Story, oder wollten wir hier nur Admin Definieren? 
Weil es nicht so in das Schema passt:  Als .. will/möchte ich ... um/weil ...

**Comment by LocoVIB** [comment]
Vielleicht das wie folgt aufsplitten?

Als Betreiber der Seite kann man Administratoren manuell erzeugen.
Als Betreiber der Seite habe ich die gleichen Rechte wie ein Admin.
