### ISSUE TITLE
Als Staat will ich wie eine Organisation sein, nur mit noch höheren Prioritäten.

### ISSUE THREAD

**Issue by LocoVIB** [actofgoods/actofgoods#54]

**Comment by d3n12** [comment]
staaten/ngos sind gleichwertig

**Comment by LocoVIB** [comment]
würde ich nicht sagen aber können wir so machen (ich würde den staaten in ihrem eigenen Land eine höhere Priorität geben)

**Comment by LocoVIB** [comment]
können wir so machen jedoch würde ich sagen das der Staat in seinem Land eine hpöhere Priorität haben sollte

**Comment by LocoVIB** [comment]
verworfen durch Kunden
